# Generated by Django 4.1.4 on 2022-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='https://zakonvremeni.ru/news/', max_length=100),
        ),
    ]
